// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrimaryPixels.Data;

#nullable disable

namespace PrimaryPixels.Migrations
{
    [DbContext(typeof(PrimaryPixelsContext))]
    partial class PrimaryPixelsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PrimaryPixels.Models.Order.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PrimaryPixels.Models.Order.OrderDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UnitPrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("PrimaryPixels.Models.Products.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Availability")
                        .HasColumnType("bit");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("TotalSold")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasDiscriminator<string>("ProductType").HasValue("Product");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PrimaryPixels.Models.ShoppingCartItem.ShoppingCartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("PrimaryPixels.Models.Products.Device", b =>
                {
                    b.HasBaseType("PrimaryPixels.Models.Products.Product");

                    b.Property<string>("Cpu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Cpu");

                    b.Property<int>("InternalMemory")
                        .HasColumnType("int")
                        .HasColumnName("InternalMemory");

                    b.Property<int>("Ram")
                        .HasColumnType("int")
                        .HasColumnName("Ram");

                    b.HasDiscriminator().HasValue("Device");
                });

            modelBuilder.Entity("PrimaryPixels.Models.Products.Headphone", b =>
                {
                    b.HasBaseType("PrimaryPixels.Models.Products.Product");

                    b.Property<bool>("Wireless")
                        .HasColumnType("bit")
                        .HasColumnName("Wireless");

                    b.HasDiscriminator().HasValue("Headphone");

                    b.HasData(
                        new
                        {
                            Id = 6,
                            Availability = true,
                            Image = "https://s13emagst.akamaized.net/products/78736/78735363/images/res_42c4ab07b083c382ac958c5abde97ccd.jpg?width=720&height=720&hash=AF0FC648A7C459193BB006D07F758597",
                            Name = "Ultra pro HP 5000",
                            Price = 500,
                            TotalSold = 0,
                            Wireless = false
                        },
                        new
                        {
                            Id = 7,
                            Availability = true,
                            Image = "https://s13emagst.akamaized.net/products/46154/46153291/images/res_3d60cf092b7bb976cb438aeb4788d04f.jpg?width=720&height=720&hash=27C95317E6A8947487149076F5F52C1E",
                            Name = "DAH6789WH Bluetooth",
                            Price = 20000,
                            TotalSold = 1,
                            Wireless = true
                        },
                        new
                        {
                            Id = 8,
                            Availability = false,
                            Image = "https://s13emagst.akamaized.net/products/78736/78735363/images/res_42c4ab07b083c382ac958c5abde97ccd.jpg?width=720&height=720&hash=AF0FC648A7C459193BB006D07F758597",
                            Name = "Kids Headphone 3000",
                            Price = 2000,
                            TotalSold = 1,
                            Wireless = false
                        },
                        new
                        {
                            Id = 9,
                            Availability = true,
                            Image = "https://s13emagst.akamaized.net/products/34948/34947038/images/res_6aff00e29067abeb44a4172c9518a711.jpg?width=720&height=720&hash=150D280D7245265AAEAB81328D899B73",
                            Name = "Ultra wireless GP",
                            Price = 3000,
                            TotalSold = 9,
                            Wireless = true
                        },
                        new
                        {
                            Id = 10,
                            Availability = true,
                            Image = "https://s13emagst.akamaized.net/products/46154/46153291/images/res_3d60cf092b7bb976cb438aeb4788d04f.jpg?width=720&height=720&hash=27C95317E6A8947487149076F5F52C1E",
                            Name = "Ultra Stereo BT 30",
                            Price = 15000,
                            TotalSold = 0,
                            Wireless = true
                        });
                });

            modelBuilder.Entity("PrimaryPixels.Models.Products.Computer", b =>
                {
                    b.HasBaseType("PrimaryPixels.Models.Products.Device");

                    b.Property<bool>("DvdPlayer")
                        .HasColumnType("bit")
                        .HasColumnName("DvdPlayer");

                    b.HasDiscriminator().HasValue("Computer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Availability = true,
                            Image = "https://s13emagst.akamaized.net/products/71331/71330955/images/res_b75e8c737204f265c382468aca168f75.jpg?width=720&height=720&hash=90CF69FDA4FFA74B09714BE0BBA2A69A",
                            Name = "Gaming PC 3510",
                            Price = 100000,
                            TotalSold = 0,
                            Cpu = "I3-6100",
                            InternalMemory = 512,
                            Ram = 8,
                            DvdPlayer = false
                        },
                        new
                        {
                            Id = 2,
                            Availability = true,
                            Image = "https://s13emagst.akamaized.net/products/16684/16683989/images/res_45eee4b6571e6820111f638716cf3bf5.jpg?width=720&height=720&hash=1823932085ED244C3F414C27A78312AC",
                            Name = "Gaming PC 5000",
                            Price = 5000000,
                            TotalSold = 0,
                            Cpu = "I5-8100",
                            InternalMemory = 1024,
                            Ram = 16,
                            DvdPlayer = false
                        },
                        new
                        {
                            Id = 3,
                            Availability = true,
                            Image = "https://s13emagst.akamaized.net/products/15188/15187279/images/res_44116bf82dc775127335f7aba3509421.jpg?width=720&height=720&hash=4F2A3C176CD289E8513E4E136C00D283",
                            Name = "Gamer PC A-I5642",
                            Price = 800000,
                            TotalSold = 3,
                            Cpu = "i9-14911KF",
                            InternalMemory = 2048,
                            Ram = 16,
                            DvdPlayer = true
                        },
                        new
                        {
                            Id = 4,
                            Availability = false,
                            Image = "https://s13emagst.akamaized.net/products/15188/15187279/images/res_44116bf82dc775127335f7aba3509421.jpg?width=720&height=720&hash=4F2A3C176CD289E8513E4E136C00D283",
                            Name = "Gamer PC A-I7689",
                            Price = 1000000,
                            TotalSold = 5,
                            Cpu = "i9-45500KJ",
                            InternalMemory = 2048,
                            Ram = 32,
                            DvdPlayer = true
                        },
                        new
                        {
                            Id = 5,
                            Availability = true,
                            Image = "https://s13emagst.akamaized.net/products/16684/16683989/images/res_45eee4b6571e6820111f638716cf3bf5.jpg?width=720&height=720&hash=1823932085ED244C3F414C27A78312AC",
                            Name = "Gamer PC C-I4567",
                            Price = 1300000,
                            TotalSold = 11,
                            Cpu = "I6-2300",
                            InternalMemory = 1024,
                            Ram = 32,
                            DvdPlayer = false
                        });
                });

            modelBuilder.Entity("PrimaryPixels.Models.Products.Phone", b =>
                {
                    b.HasBaseType("PrimaryPixels.Models.Products.Device");

                    b.Property<bool>("CardIndependency")
                        .HasColumnType("bit")
                        .HasColumnName("CardIndependency");

                    b.HasDiscriminator().HasValue("Phone");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            Availability = true,
                            Image = "https://s13emagst.akamaized.net/products/49762/49761516/images/res_a3c8676c0043ba09f646d836b7fc37bb.jpg?width=720&height=720&hash=30109537CDA74ED1D82D5D87E13E5BE1",
                            Name = "Redmi A24",
                            Price = 100000,
                            TotalSold = 0,
                            Cpu = "Dimensity 9400",
                            InternalMemory = 128,
                            Ram = 4,
                            CardIndependency = true
                        },
                        new
                        {
                            Id = 12,
                            Availability = true,
                            Image = "https://s13emagst.akamaized.net/products/62470/62469084/images/res_119d9158060ffab289ace1eb4fb5f285.jpg?width=720&height=720&hash=2025575EAA3830851B708B6666E37773",
                            Name = "iPhone 19",
                            Price = 5000000,
                            TotalSold = 0,
                            Cpu = "Dimensity 11000",
                            InternalMemory = 512,
                            Ram = 16,
                            CardIndependency = false
                        },
                        new
                        {
                            Id = 13,
                            Availability = true,
                            Image = "https://s13emagst.akamaized.net/products/57643/57642529/images/res_77d22d24346a96ca4e3f4e7a9eeea779.jpg?width=720&height=720&hash=61507AB28D44CE94F541B937B7FB239C",
                            Name = "Redmi A29",
                            Price = 600000,
                            TotalSold = 0,
                            Cpu = "Dimensity 9800",
                            InternalMemory = 256,
                            Ram = 8,
                            CardIndependency = true
                        },
                        new
                        {
                            Id = 14,
                            Availability = false,
                            Image = "https://s13emagst.akamaized.net/products/62470/62469084/images/res_119d9158060ffab289ace1eb4fb5f285.jpg?width=720&height=720&hash=2025575EAA3830851B708B6666E37773",
                            Name = "Samsung Galaxy E100",
                            Price = 260000,
                            TotalSold = 2,
                            Cpu = "Exynos 4520",
                            InternalMemory = 256,
                            Ram = 8,
                            CardIndependency = false
                        },
                        new
                        {
                            Id = 15,
                            Availability = true,
                            Image = "https://s13emagst.akamaized.net/products/57643/57642529/images/res_77d22d24346a96ca4e3f4e7a9eeea779.jpg?width=720&height=720&hash=61507AB28D44CE94F541B937B7FB239C",
                            Name = "HONOR AZC",
                            Price = 105000,
                            TotalSold = 8,
                            Cpu = "Exynos 3434",
                            InternalMemory = 128,
                            Ram = 16,
                            CardIndependency = true
                        });
                });

            modelBuilder.Entity("PrimaryPixels.Models.Order.OrderDetails", b =>
                {
                    b.HasOne("PrimaryPixels.Models.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PrimaryPixels.Models.ShoppingCartItem.ShoppingCartItem", b =>
                {
                    b.HasOne("PrimaryPixels.Models.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
