services:
  frontend:
    build:
      context: Frontend/vite-project
    ports:
      - 4000:4000
    

  backend:
    build:
      context: PrimaryPixels
    env_file:
      - .env
    ports:
      - 8000:8080
    # Only start backend when the DB is running
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mcr.microsoft.com/mssql/server
    env_file:
      - .env
    ports:
      - 1434:1433
    # Check if the DB server is available
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/1433"]
      interval: 30s
      retries: 10
      start_period: 60s
      timeout: 20s
    
   
